---
- hosts: server03
  sudo: yes

  tasks:
  - name: Disabilitando SELinux
    selinux:
     state: disabled

  - name: Desabilitando Firewall
    service:
       name: firewalld
       state: stopped
       enabled: False

  - name: Instalacao Banco
    yum:
      name: mariadb-server
      state: present

  - name: Reiniciando banco
    service:
      name: mariadb
      state: restarted

  - name: Instalacao Apache
    yum:
      name: httpd
      state: present

  - name: Iniciando o Apache
    service:
      name: httpd
      state: started
