---
- name: jenkins && docker
  hosts: server04

  tasks:
  - name: Disabilitando SELinux
    selinux:
     state: disabled

  - name: Desabilitando Firewall
    service:
       name: firewalld
       state: stopped
       enabled: False
       
   - name: Adicionando repositorio do Docker
     get_url:
       url: https://download.docker.com/linux/centos/docker-ce.repo
       dest: /etc/yum.repos.d/docer-ce.repo

   - name: Adicionando repositorio do Jenkins
     command: wget -O /etc/yum.repos.d/jenkins.repo https://pkg.jenkins.io/redhat-stable/jenkins.repo

   - name: Importando Chave do Jenkins
     rpm_key:
      key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key
      state: present

   - name: Instalacao Java
     yum:
      name: java
      state: present

   - name: Instalacao jenkins
     yum:
      name: jenkins
      state: present

   - name: Instalacao docker
     yum:
      name: docker
      state: present

   - name: Habilitando a porta 8080
     shell: iptables -I INPUT -p tcp --dport 8080 -m state --state NEW,ESTABLISHED -j ACCEPT

   - name: Iniciando servico jenkins
     service:
        name: jenkins
        state: started

   - name: Iniciando servico docker
     service:
        name: docker
        state: started
