---
- hosts: server03
  sudo: yes

  tasks:
  - name: Instalacao Banco
    yum:
      name: mariadb-server
      state: present

  - name: Reiniciando banco
    service:
      name: mariadb
      state: restarted

  - name: Instalacao Apache
    yum:
      name: httpd
      state: present

  - name: echo
    shell: echo "helloword" > /var/www/html/info.php

  - name: Reiniciando Apache
    service:
      name: httpd
      state: restarted

  - name: Reiniciando Apache
    service:
      name: httpd
      state: started

  - name: Desabilitando Firewall
    service:
       name: firewalld
       state: stopped
       enabled: False
