---
- name: jenkins && docker
  hosts: 192.168.194.154

  tasks:

   - name: Add Docker repo
     get_url:
       url: https://download.docker.com/linux/centos/docker-ce.repo
       dest: /etc/yum.repos.d/docer-ce.repo
       
   - name: Download jenkins repo
     command: wget -O /etc/yum.repos.d/jenkins.repo https://pkg.jenkins.io/redhat-stable/jenkins.repo

   - name: Import Jenkins CI key
     rpm_key:
      key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key
      state: present
       
   - name: Instalacao Java
     yum:
      name: java
      state: present
       
   - name: Instalacao jenkins
     yum:
      name: jenkins
      state: present     
       
   - name: Instalacao docker
     yum:
      name: docker
      state: present        
   
   - name: Habilitando a porta 8080
     shell: iptables -I INPUT -p tcp --dport 8080 -m state --state NEW,ESTABLISHED -j ACCEPT
     
   - name: Iniciando serviço jenkins
     service:
        name: jenkins
        state: started
        
   - name: Iniciando serviço docker
     service:
        name: docker
        state: started