---
- hosts: 192.168.194.154
  sudo: yes

  tasks:
  - name: Instalacao Banco
    yum:
      name: mariadb-server
      state: present
      
  - name: Reiniciando banco
    service:
      name: mariadb
      state: restarted
      
  - name: Instalacao Apache
    yum:
      name: httpd
      state: present
      
  - name: echo
    shell: echo "helloword" > /var/www/html/info.php

  - name: Reiniciando Apache
    service:
      name: httpd
      state: restarted
      
  - name: Reiniciando Apache
    service:
      name: httpd
      state: started
    
  - name: habilitar porta
    shell: firewall-cmd --permanent --zone=trusted --add-port=8080/tcp
    
  - name: habilitar porta
    shell: firewall-cmd --permanent --zone=trusted --add-port=80/tcp